version: "3"
tasks:
  build: 
    cmds:
      - (docker network inspect mockten_nw > /dev/null 2>&1 || docker network create mockten_nw)
      - (cd mysql && docker run --rm -d --name mysql-service.default.svc.cluster.local -e MYSQL_ROOT_PASSWORD=rootpassword -e MYSQL_DATABASE=mocktendb -e MYSQL_USER=mocktenusr -e MYSQL_PASSWORD=mocktenpassword --network mockten_nw -p 3306:3306 mockten-mysql)
      - (cd redis && docker run --rm -d --name redis-service.default.svc.cluster.local --network mockten_nw -p 6379:6379 mockten-redis)
      - (cd uam && docker run --rm --platform linux/amd64 --name uam-service.default.svc.cluster.local --network mockten_nw -e KC_HOSTNAME=localhost -dit uam)
      - (cd minio && docker run --rm --name minio-service.default.svc.cluster.local --network mockten_nw -p 9000:9000 -p 9001:9001 -dit minio)
      - (cd apigw && docker run --rm --name apigw --network mockten_nw -p 8082:8082 -p 8001:8001 -p 8002:8002 -dit apigw)
      - (cd meilisearch && docker run --rm --name meilisearch-service.default.svc.cluster.local --network mockten_nw -p 7700:7700 -dit meilisearch)
      - (cd searchitem && docker run --rm --name searchitem-service.default.svc.cluster.local --network mockten_nw -p 50051:50051 -dit searchitem)
      - (cd sync && docker run --rm --name mockten-sync --network mockten_nw -dit mockten-sync)
      - (cd geocoding && docker run --rm -d -v "$PWD/config.json:/app/config.json:ro" --name geocoding-service.default.svc.cluster.local --network mockten_nw mockten-geocoding)
      - (docker run --rm --name nginx --network mockten_nw -v $(pwd)/dev_nginx.conf:/etc/nginx/nginx.conf:ro -p 80:80 -dit nginx)
      - (cd ecfront2 && npm run dev -- --host 0.0.0.0 --port 5173)
  destroy: 
    cmds:
      - docker stop mockten-sync
      - docker ps --no-trunc | awk '$NF ~ /-service\.default\.svc\.cluster\.local$/ { print $NF }' | xargs -r docker stop
      - docker stop nginx
      - docker stop apigw
      - docker network rm mockten_nw
  setup:
    cmds:
      - (cd redis && docker build -t mockten-redis .)
      - (cd mysql && docker build -t mockten-mysql .)
      - (cd uam && docker build --platform linux/amd64 -t uam .)
      - (cd apigw && docker build -t apigw .)
      - (cd minio && docker build -t minio . )
      - (cd meilisearch && docker build -t meilisearch .)
      - (cd searchitem && docker build -t searchitem .)
      - (cd sync && docker build -t mockten-sync .)
      - (cd geocoding && docker build -t mockten-geocoding .)