version: '3.9'

services:
  kong-database:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong:
    image: kong/kong-gateway:2.8.1.0-alpine
    user: root
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_CASSANDRA_CONTACT_POINTS: "kong-database"
      KONG_PROXY_LISTEN: "0.0.0.0:8082"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "8082:8082"
      - "8001:8001"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
    entrypoint: ["/bin/sh", "-c", "
      apk update && apk add --no-cache wget &&
      kong migrations bootstrap &&
      kong start &&
      sleep 10 &&
      wget --method=POST --body-data='name=keycloak&host=host.docker.internal&port=8080&protocol=http' http://localhost:8001/services/ &&
      wget --method=POST --body-data='paths[]=/realms/mockten-realm-dev/protocol/openid-connect&strip_path=false' http://localhost:8001/services/keycloak/routes &&
      wget --method=POST --body-data='paths[]=/api/uam&strip_path=false' http://localhost:8001/services/keycloak/routes &&
      wget --method=POST --header='Content-Type: application/json' --body-data='{
        \"name\": \"cors\",
        \"config\": {
          \"origins\": [\"http://localhost:5173\"],
          \"methods\": [\"GET\", \"POST\", \"PUT\", \"DELETE\"],
          \"headers\": [\"Authorization\", \"Content-Type\", \"Accept\"],
          \"exposed_headers\": [\"Authorization\", \"Content-Length\", \"Accept\"],
          \"credentials\": true,
          \"max_age\": 3600
        }
      }' http://localhost:8001/services/keycloak/plugins -O - &&
      tail -f /dev/null
    "]

