version: '3.9'

services:
  kong:
    image: kong/kong-gateway:2.8.1.0-alpine
    user: root
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_LISTEN: "0.0.0.0:8082"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_LISTEN: "0.0.0.0:8002"
      KONG_DECLARATIVE_CONFIG: "/kong/kong.yaml" 
    volumes:
      - ./kong.yaml:/kong/kong.yaml 
    ports:
      - "8082:8082"
      - "8001:8001"
      - "8002:8002"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
    entrypoint: ["/bin/sh", "-c", "
      set -x &&
      apk update &&
      kong migrations bootstrap &&
      kong start --vv &&
      tail -f /dev/null
    "]