name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build_ecfront:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ecfront
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v .

   # - name: Test
   #  run: go test -v .

  push_snapshot_container_ecfront:
    needs: [build_ecfront]
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ecfront
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1
    - name: GCP Authenticate
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Setup GCloud
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: Configure docker to use the gcloud cli
      run: gcloud auth configure-docker --quiet

    - name: Get latest version
      id: get-latest-version
      run: |
        export LATEST_VERSION=$(gcloud container images list-tags gcr.io/${{ secrets.GCP_PROJECT_ID }}/ecfront --format='get(tags)' --limit=1)
        echo "::set-output name=latest_version::$LATEST_VERSION"

    - name: Increment patch version
      id: increment-patch-version
      run: |
        export PATCH_VERSION=$((${{ steps.get-latest-version.outputs.latest_version }} + 1))
        echo "::set-output name=patch_version::$PATCH_VERSION"

    - name: Build and push container
      run: |
        export IMAGE_TAG="gcr.io/${{ secrets.GCP_PROJECT_ID }}/ecfront:v0.0.${{ steps.increment-patch-version.outputs.patch_version }}"
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG


  build_ecpay:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ecpay
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v .

    # - name: Test
    #  run: go test -v .


  push_snapshot_container_ecpay:
    needs: [build_ecpay]
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ecpay
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1
    - name: GCP Authenticate
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Setup GCloud
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: Configure docker to use the gcloud cli
      run: gcloud auth configure-docker --quiet

    - name: Get latest version
      id: get-latest-version
      run: |
        export LATEST_VERSION=$(gcloud container images list-tags gcr.io/${{ secrets.GCP_PROJECT_ID }}/ecpay --format='get(tags)' --limit=1)
        echo "::set-output name=latest_version::$LATEST_VERSION"

    - name: Increment patch version
      id: increment-patch-version
      run: |
        export PATCH_VERSION=$((${{ steps.get-latest-version.outputs.latest_version }} + 1))
        echo "::set-output name=patch_version::$PATCH_VERSION"

    - name: Build and push container
      run: |
        export IMAGE_TAG="gcr.io/${{ secrets.GCP_PROJECT_ID }}/ecpay:v0.0.${{ steps.increment-patch-version.outputs.patch_version }}"
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG


  build_notification:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: notification
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v .

    # - name: Test
    #  run: go test -v .


  push_snapshot_container_notification:
    needs: [build_notification]
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: notification
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1
    - name: GCP Authenticate
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Setup GCloud
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: Configure docker to use the gcloud cli
      run: gcloud auth configure-docker --quiet

    - name: Get latest version
      id: get-latest-version
      run: |
        export LATEST_VERSION=$(gcloud container images list-tags gcr.io/${{ secrets.GCP_PROJECT_ID }}/notification --format='get(tags)' --limit=1)
        echo "::set-output name=latest_version::$LATEST_VERSION"

    - name: Increment patch version
      id: increment-patch-version
      run: |
        export PATCH_VERSION=$((${{ steps.get-latest-version.outputs.latest_version }} + 1))
        echo "::set-output name=patch_version::$PATCH_VERSION"

    - name: Build and push container
      run: |
        export IMAGE_TAG="gcr.io/${{ secrets.GCP_PROJECT_ID }}/notification:v0.0.${{ steps.increment-patch-version.outputs.patch_version }}"
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG

  build_payexecution:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: payexecution
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

  push_snapshot_container_payexecution:
    needs: [build_payexecution]
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: payexecution
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1
    - name: GCP Authenticate
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Setup GCloud
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: Configure docker to use the gcloud cli
      run: gcloud auth configure-docker --quiet

    - name: Get latest version
      id: get-latest-version
      run: |
        export LATEST_VERSION=$(gcloud container images list-tags gcr.io/${{ secrets.GCP_PROJECT_ID }}/payexecution --format='get(tags)' --limit=1)
        echo "::set-output name=latest_version::$LATEST_VERSION"

    - name: Increment patch version
      id: increment-patch-version
      run: |
        export PATCH_VERSION=$((${{ steps.get-latest-version.outputs.latest_version }} + 1))
        echo "::set-output name=patch_version::$PATCH_VERSION"

    - name: Build and push container
      run: |
        export IMAGE_TAG="gcr.io/${{ secrets.GCP_PROJECT_ID }}/payexecution:v0.0.${{ steps.increment-patch-version.outputs.patch_version }}"
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG

  build_ranking:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ranking
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v .

    # - name: Test
    #  run: go test -v .

  push_snapshot_container_ranking:
    needs: [build_ranking]
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ranking
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1
    - name: GCP Authenticate
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Setup GCloud
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: Configure docker to use the gcloud cli
      run: gcloud auth configure-docker --quiet

    - name: Get latest version
      id: get-latest-version
      run: |
        export LATEST_VERSION=$(gcloud container images list-tags gcr.io/${{ secrets.GCP_PROJECT_ID }}/ranking --format='get(tags)' --limit=1)
        echo "::set-output name=latest_version::$LATEST_VERSION"

    - name: Increment patch version
      id: increment-patch-version
      run: |
        export PATCH_VERSION=$((${{ steps.get-latest-version.outputs.latest_version }} + 1))
        echo "::set-output name=patch_version::$PATCH_VERSION"

    - name: Build and push container
      run: |
        export IMAGE_TAG="gcr.io/${{ secrets.GCP_PROJECT_ID }}/ranking:v0.0.${{ steps.increment-patch-version.outputs.patch_version }}"
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG


  build_searchitem:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: searchitem
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v .

    # - name: Test
    #  run: go test -v .

  push_snapshot_container_searchitem:
    needs: [build_searchitem]
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: searchitem
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1
    - name: GCP Authenticate
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Setup GCloud
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: Configure docker to use the gcloud cli
      run: gcloud auth configure-docker --quiet

    - name: Get latest version
      id: get-latest-version
      run: |
        export LATEST_VERSION=$(gcloud container images list-tags gcr.io/${{ secrets.GCP_PROJECT_ID }}/searchitem --format='get(tags)' --limit=1)
        echo "::set-output name=latest_version::$LATEST_VERSION"

    - name: Increment patch version
      id: increment-patch-version
      run: |
        export PATCH_VERSION=$((${{ steps.get-latest-version.outputs.latest_version }} + 1))
        echo "::set-output name=patch_version::$PATCH_VERSION"

    - name: Build and push container
      run: |
        export IMAGE_TAG="gcr.io/${{ secrets.GCP_PROJECT_ID }}/searchitem:v0.0.${{ steps.increment-patch-version.outputs.patch_version }}"
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG
