name: payexecution_pr

on:
  pull_request_target:
    types:
      - opened
    paths:
      - 'payexecution/**'

defaults:
  run:
    working-directory: payexecution

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

  snapshot_build:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: GCP Authenticate
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Setup GCloud
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'
    - name: Configure docker to use the gcloud cli
      run: gcloud auth configure-docker --quiet
    - name: Build a docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/payexecution_snapshot:${GITHUB_SHA::7} .