name: ranking_pr

on:
  pull_request_target:
    types:
      - opened
    paths:
      - 'ranking/**'

defaults:
  run:
    working-directory: ranking

jobs:
  build_ranking:
    runs-on: ubuntu-latest
    env:
      GOROOT: "/opt/hostedtoolcache/go/1.18.10/x64"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v .

   # - name: Test
   #  run: go test -v .

  build_container_snapshot:
    needs: [build_ranking]
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: GCP Authenticate
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Setup GCloud
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'
    - name: Configure docker to use the gcloud cli
      run: gcloud auth configure-docker --quiet
    - name: Build a docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/ranking_snapshot:${GITHUB_SHA::7} .